name: Houdini Docker Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install docker.io
          sudo usermod -aG docker $USER
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Verify Docker and Docker Compose installation
        run: |
          docker-compose --version
          docker --version

      - name: Run Hello, World! test with Docker
        run: |
          docker run --rm hello-world
